一般ユーザー向けのAPI定義
dacq-trap/dacq pull request #6
Opened 2022-06-11 13:26 UTC by oribe1115

2022-06-14 11:52 UTC, logica0419 requested changes
素晴らしい完成度です、流石…
ありがとうございます
気になるところをバッとリストアップしたので確認お願いします
あともう一つ、cidとかtidとかの略し方、悪くは無いと思うんですけど明示的(親切)でないなぁと思っていて、略してcompIdくらいまでが親切かなと思います
いだてんさんもこれを元に実装していくのである程度手厚くしたいなと考えていますが、どう思いますか？

2022-06-14 11:52 UTC, logica0419 commented on schema/openapi/openapi.yaml
> +    $ref: ./paths/competitions/cid.leaderboard.yaml
parameter忘れてるかも
別yamlに書かれてるなら統一してほしいです

2022-06-14 11:52 UTC, logica0419 commented on schema/openapi/paths/competitions/cid.leaderboard.yaml
> +                - submittedAt
leaderboard用のスキーマ完全に忘れていたのでこの後ドメインに定義し直そうと思います
「leaderboard」でcommonディレクトリに抜き出しお願いできますか？

2022-06-14 11:52 UTC, logica0419 commented on schema/openapi/paths/competitions/cid.yaml
> +        コンペティションに参加登録済みです
これConflictに分割した方が綺麗な気がするので、Conflictの追加お願いできますか？

2022-06-14 11:52 UTC, logica0419 commented on schema/openapi/paths/competitions/cid.yaml
> +  operationId: joinCompetition
これ、意味合い的に`POST /competition/{cid}/teams`か`POST /teams`の方が近いと思ってるんですけど(コンペへの参加がチームの作成とイコールなので)、これについてどう思います？
チームの作成としてしまった方が、名前とかちゃんとPOSTしてできるので良いと個人的に思ってます

2022-06-14 11:52 UTC, logica0419 commented on schema/openapi/paths/teams/tid.yaml
> +  summary: チームのの詳細を取得
typo

2022-06-14 11:52 UTC, logica0419 commented on schema/openapi/paths/teams/tid.merge.yaml
> +            $ref: ../../common/mergeRequest.yaml
ここArrayであるべきかなと一瞬思ったんですが、仕様としてMerge Requestを出している / 出されているチームは新たなMRを出せないという方針で行くなら納得が行きます
想定しているのはこの方針で合ってますか？

2022-06-14 12:28 UTC, oribe1115 reviewed
とりあえずディスカッション系のコメントへの返信を返しました

2022-06-14 12:28 UTC, oribe1115 commented on schema/openapi/common/judgement.yaml
> +  - scoreOrder
開発のベースとしてDomainのをほぼ丸移植した形なので、実装を始めた後にでもAPI露出の実態に合わせて変更してもらえれば

2022-06-14 12:28 UTC, oribe1115 commented on schema/openapi/paths/competitions/cid.yaml
> +        コンペティションに参加登録済みです
以下の理由から「Conflictとしてコンポーネントに切り出す」のはやりたくないなぁという気持ちです
- ステータス400そのものにはConflictの意味合いはない
- ステータス400の理由が一意に「コンフリクトが発生するので不可である」に定まるのはこのAPIくらいなので、取り回し前提で切り出して乱用されたくない

2022-06-14 12:28 UTC, oribe1115 commented on schema/openapi/paths/teams/tid.merge.yaml
> +            $ref: ../../common/mergeRequest.yaml
「完了していないMerge Requestがあるチームは新たにマージ処理をできない」という認識でいました
isMergingはここで使うのかなと
ので、そのつもりで単体オブジェクトにしました

人数制限的にこのロジックにしておくのがシンプルでわかりやすいと思っていますが、並行して複数のMerge Requestを立てられるようにするのがよさそう、ということならそれでもいいと思います

2022-06-14 12:28 UTC, oribe1115 commented on schema/openapi/paths/competitions/cid.yaml
> +  operationId: joinCompetition
チーム名をここで入力させた方がいいのは:tashikani:
`POST /competition/{cid}/teams`がAPIの構成としてわかりやすそうなのでそれにします

2022-06-14 12:32 UTC, oribe1115 commented
> あともう一つ、cidとかtidとかの略し方、悪くは無いと思うんですけど明示的(親切)でないなぁと思っていて、略してcompIdくらいまでが親切かなと思います

あんまりpath parameterの名称が長いとSwaggerで一覧で見たときに横に長くなりすぎて見にくいかな、と思ってこうしました
一応各APIの詳細を開いたときには`competitionId`などの名前と説明が表示されるようにはなっているはずなので、それで明示性は足りるかなという認識です
特にこだわりがある部分ではないので、明示的な名称にした方がいいということであれば変えます

2022-06-14 12:38 UTC, logica0419 commented
あーそっか、パラメーターの詳細で正式名称を書いてあるのか
ごめんなさい、OpenAPIの仕様理解してなかったです
それなら全く問題ないです！

2022-06-14 12:40 UTC, oribe1115 commented
コードの修正箇所pushしました

2022-06-14 12:41 UTC, logica0419 commented on schema/openapi/paths/competitions/cid.yaml
> +  operationId: joinCompetition
そしたらそっちに移行をお願いしたいです〜

2022-06-14 12:43 UTC, logica0419 commented on schema/openapi/paths/competitions/cid.yaml
> +        コンペティションに参加登録済みです
あ、ごめんなさい
レスポンススキーマの話ではなくて、409のConfictステータスコードを使ってほしいという意味でした、紛らわしくて申し訳ないです
Bad Requestがそれ以外の理由で起こらないなら400を削除していただく方針で…

2022-06-14 12:49 UTC, logica0419 commented on schema/openapi/paths/teams/tid.merge.yaml
> +            $ref: ../../common/mergeRequest.yaml
そのロジックがシンプルでわかりやすいのでこのままでお願いします
isMerging、確か僕は新規メンバー追加を制限するため(所属がわかりにくくなる・合計数を計算しなければいけなくなる)に使おうとしてた気がしますが、その目的でも使えそうですね、ありがとうございます

2022-06-14 19:58 UTC, logica0419 commented
あと409の問題だけ合意が取れたらマージしますね

2022-06-15 03:18 UTC, oribe1115 commented on schema/openapi/paths/competitions/cid.yaml
> +        コンペティションに参加登録済みです
409ステータスの存在忘れてた
変更しました

2022-06-15 06:42 UTC, logica0419 approved these changes
本来僕がやるべきところをやっていただいて、大変ありがとうございました
今回見つけきれなかったバグは後々こちらで直していきますね

2022-06-15 06:42 UTC, merged